language:
  - node_js

node_js:
  - "9"

addons:
  chrome: stable

before_script:
  - npm install -g @angular/cli

before_install:
  - npm install

script:
  - ng test --browsers ChromeHeadless --single-run
