language:
  - node_js

node_js:
  - "9"

addons:
  chrome: stable

cache:
  directories:
  - node_modules

before_script:
  - npm install -g @angular/cli

before_install:
  - npm install

script:
  - ng test